# Generated by Django 5.0.7 on 2024-08-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('letter', models.CharField(max_length=1)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
